# Generated by Django 6.0 on 2026-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id_cuenta_corriente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cuenta_corriente',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'moneda',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id_movimiento_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0, max_digits=100), max_digits=100)),
            ],
            options={
                'db_table': 'movimiento_cuenta',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subcategoria',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id_tipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_movimiento',
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id_tipo_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_transaccion',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
            options={
                'db_table': 'transaccion',
            },
        ),
    ]
