# Generated by Django 6.0 on 2026-02-27 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.persona'),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.moneda'),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='cuenta_corriente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.cuentacorriente'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.categoria'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.subcategoria'),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.tipomovimiento'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.metodopago'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.moneda'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='movimiento_cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.movimientocuenta'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.persona'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.subcategoria'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo_transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.tipotransaccion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
