# Generated by Django 6.0 on 2026-02-28 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocuenta',
            name='subcategoria',
        ),
    ]
