# Generated by Django 6.0 on 2026-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_movimientocuenta_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuenta',
            name='concepto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='concepto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
