# Generated by Django 6.0 on 2026-02-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_movimientocuenta_concepto_transaccion_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuenta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
