# Generated by Django 6.0 on 2026-02-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_movimientocuenta_activo_transaccion_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='estado',
            new_name='activo',
        ),
    ]
