# Generated by Django 6.0 on 2026-03-03 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_estado_transaccion_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
